"""creation tables initiales

Revision ID: eef917ee3602
Revises: 
Create Date: 2026-10-01 21:03:25.791057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef917ee3602'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logement',
    sa.Column('logement_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('type_logement', sa.String(length=30), nullable=False),
    sa.Column('capacite', sa.Integer(), nullable=False),
    sa.Column('prix_par_nuit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("type_logement IN ('STUDIO', 'APPARTEMENT', 'MAISON', 'CHAMBRE')", name='ck_logement_type'),
    sa.CheckConstraint('capacite > 0', name='ck_logement_capacite'),
    sa.CheckConstraint('prix_par_nuit > 0', name='ck_logement_prix'),
    sa.PrimaryKeyConstraint('logement_id')
    )
    op.create_index(op.f('ix_logement_ville'), 'logement', ['ville'], unique=False)
    op.create_table('utilisateur',
    sa.Column('user_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='CLIENT', nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_inscription', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("role IN ('CLIENT', 'ADMIN')", name='ck_utilisateur_role'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    op.create_table('reservation',
    sa.Column('reservation_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logement_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('nombre_personnes', sa.Integer(), nullable=False),
    sa.Column('prix_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=20), server_default='CONFIRMEE', nullable=False),
    sa.Column('date_reservation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("statut IN ('CONFIRMEE', 'ANNULEE', 'TERMINEE')", name='ck_reservation_statut'),
    sa.CheckConstraint('date_fin > date_debut', name='ck_reservation_dates'),
    sa.CheckConstraint('nombre_personnes > 0', name='ck_reservation_nb_personnes'),
    sa.CheckConstraint('prix_total >= 0', name='ck_reservation_prix'),
    sa.ForeignKeyConstraint(['logement_id'], ['logement.logement_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateur.user_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_index('ix_reservation_logement_dates', 'reservation', ['logement_id', 'date_debut', 'date_fin'], unique=False)
    op.create_index(op.f('ix_reservation_logement_id'), 'reservation', ['logement_id'], unique=False)
    op.create_index(op.f('ix_reservation_user_id'), 'reservation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_user_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_logement_id'), table_name='reservation')
    op.drop_index('ix_reservation_logement_dates', table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_index(op.f('ix_logement_ville'), table_name='logement')
    op.drop_table('logement')
    # ### end Alembic commands ###
